name: MSVC-CI
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configure and Build
        run: |
          git clone https://github.com/zrax/pycdc.git pycdc
          cd pycdc
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A Win32 ..
          cmake --build . --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pycdc-release
          path: .\pycdc\build\Release\*.exe


